#!/bin/bash

rand_seed=10
save_dir=0326_test/$2
num_batches=200
max_epoch=80
comm_cmd=" --on-local "

folder_path=$1
config_path=${folder_path}/pre/config.yaml
checkpoint_path=${folder_path}/pre/last.pth

set -e pipefail
#baseline
function run_pipeline {

  python run_infonce_semi.py ${comm_cmd} --save_dir ${save_dir} -n acdc -b ${num_batches} -e ${max_epoch} -s ${rand_seed} \
    --time=2 --arch_checkpoint=${checkpoint_path} baseline

  # mean teacher
  python run_infonce_semi.py ${comm_cmd} --save_dir ${save_dir} -n acdc -b ${num_batches} -e ${max_epoch} -s ${rand_seed} \
    --time=2 --arch_checkpoint=${checkpoint_path} meanteacher --mt_weight 0.00001

  python run_infonce_semi.py ${comm_cmd} --save_dir ${save_dir} -n acdc -b ${num_batches} -e ${max_epoch} -s ${rand_seed} \
    --time=2 --arch_checkpoint=${checkpoint_path} meanteacher --mt_weight 0.0001

  python run_infonce_semi.py ${comm_cmd} --save_dir ${save_dir} -n acdc -b ${num_batches} -e ${max_epoch} -s ${rand_seed} \
    --time=2 --arch_checkpoint=${checkpoint_path} meanteacher --mt_weight 0.001

  python run_infonce_semi.py ${comm_cmd} --save_dir ${save_dir} -n acdc -b ${num_batches} -e ${max_epoch} -s ${rand_seed} \
    --time=2 --arch_checkpoint=${checkpoint_path} meanteacher --mt_weight 0.01

  # infonce
  python run_infonce_semi.py ${comm_cmd} --save_dir ${save_dir} -n acdc -b ${num_batches} -e ${max_epoch} -s ${rand_seed} \
    --time=2 --arch_checkpoint=${checkpoint_path} infonce --info_weight 0.00001 --config_path=${config_path}

  python run_infonce_semi.py ${comm_cmd} --save_dir ${save_dir} -n acdc -b ${num_batches} -e ${max_epoch} -s ${rand_seed} \
    --time=2 --arch_checkpoint=${checkpoint_path} infonce --info_weight 0.0001 --config_path=${config_path}

  python run_infonce_semi.py ${comm_cmd} --save_dir ${save_dir} -n acdc -b ${num_batches} -e ${max_epoch} -s ${rand_seed} \
    --time=2 --arch_checkpoint=${checkpoint_path} infonce --info_weight 0.001 --config_path=${config_path}

  python run_infonce_semi.py ${comm_cmd} --save_dir ${save_dir} -n acdc -b ${num_batches} -e ${max_epoch} -s ${rand_seed} \
    --time=2 --arch_checkpoint=${checkpoint_path} infonce --info_weight 0.01 --config_path=${config_path}
}
run_pipeline
checkpoint_path=null
run_pipeline