#!/bin/bash
set -e pipefail
rand_seed=10
save_dir=0315
group_num=10
num_batches=200
pre_max_epoch=120
ft_max_epoch=80
comm_cmd=" --on-local "

python run_infonce_pretrain.py ${comm_cmd} --save_dir ${save_dir} -n acdc -b ${num_batches} -s ${rand_seed} --time=2 \
  baseline -e ${ft_max_epoch}

#### multitask
python run_infonce_pretrain.py ${comm_cmd} --save_dir ${save_dir} -n acdc -b ${num_batches} -s ${rand_seed} --time=4 \
  multitask --global_features Conv5 --global_importance 1 --contrast_on partition -g=${group_num} \
  -pe ${pre_max_epoch} -fe ${ft_max_epoch}

python run_infonce_pretrain.py ${comm_cmd} --save_dir ${save_dir} -n acdc -b ${num_batches} -s ${rand_seed} --time=4 \
  multitask --global_features Conv5 --global_importance 1 --contrast_on patient -g=${group_num} \
  -pe ${pre_max_epoch} -fe ${ft_max_epoch}

python run_infonce_pretrain.py ${comm_cmd} --save_dir ${save_dir} -n acdc -b ${num_batches} -s ${rand_seed} --time=4 \
  multitask --global_features Conv5 --global_importance 1 --contrast_on cycle -g=${group_num} \
  -pe ${pre_max_epoch} -fe ${ft_max_epoch}

#### self-paced
function run_selfapced {
  python run_infonce_pretrain.py ${comm_cmd} --save_dir ${save_dir} -n acdc -b ${num_batches} -s ${rand_seed} --time=$1 \
  selfpaced --global_features Conv5 --global_importance 1 --contrast_on partition -g=${group_num} \
  -pe ${pre_max_epoch} -fe ${ft_max_epoch} --begin_value $1 --end_value $2

python run_infonce_pretrain.py ${comm_cmd} --save_dir ${save_dir} -n acdc -b ${num_batches} -s ${rand_seed} --time=$1 \
  selfpaced --global_features Conv5 --global_importance 1 --contrast_on patient -g=${group_num} \
  -pe ${pre_max_epoch} -fe ${ft_max_epoch} --begin_value $1 --end_value $2

python run_infonce_pretrain.py ${comm_cmd} --save_dir ${save_dir} -n acdc -b ${num_batches} -s ${rand_seed} --time=$1 \
  selfpaced --global_features Conv5 --global_importance 1 --contrast_on cycle -g=${group_num} \
  -pe ${pre_max_epoch} -fe ${ft_max_epoch} --begin_value $1 --end_value $2
}
run_selfapced 4 10
run_selfapced 4 12
run_selfapced 4 17
run_selfapced 4 22
run_selfapced 4 40

