InfoNCEParameters:
  GlobalParams:
    method_name: supcontrast
  DenseParams:
    include_all: true
  LossParams:
    temperature: 0.07
  weight: 0.1

ProjectorParams:
  GlobalParams:
    feature_names: [ Conv5, ]
    feature_importance: [ 1]
    head_type: mlp
    normalize: true
    pool_name: adaptive_avg # adaptive_max #identical

  DenseParams:
    feature_names: null
    feature_importance: [ 0.05 ]
    head_type: mlp
    normalize: false # in order to perform pooling manually`1
    pool_name: identical # adaptive_max #identical
    spatial_size: [ 16, 16 ]