# this file is for infonce with the interface of `main_infonce.py`
InfoNCEParameters:
  GlobalParams:
    contrast_on: partition
  DenseParams:
    include_all: true
  LossParams:
    temperature: 0.07
  weight: 0.1
Optim:
  pre_lr: null
  ft_lr: null
ProjectorParams:
  GlobalParams:
    feature_names: [ Conv5, ]
    feature_importance: [ 1 ]
    head_type: mlp
    normalize: true
    pool_name: adaptive_avg # adaptive_max #identical


  DenseParams:
    feature_names: null
    feature_importance: [ ]
    head_type: mlp
    normalize: false # in order to perform pooling manually`1
    pool_name: identical # adaptive_max #identical
    spatial_size: 16
    pool_method: adaptive_avg

Trainer:
  pre_max_epoch: null
  ft_max_epoch: null