InfoNCEParameters:
  GlobalParams:
    contrast_on: partition
  DenseParams:
    include_all: true
  LossParams:
    temperature: 0.07
    exclude_other_pos: false
  weight: 0.1
Optim:
  pre_lr: null
  ft_lr: null
ProjectorParams:
  GlobalParams:
    feature_names: [ Conv5, ]
    feature_importance: [ 1 ]
    head_type: mlp
    normalize: true
    pool_name: adaptive_avg # adaptive_max #identical
    softweight: 0.1

  DenseParams:
    feature_names: [ ]
    feature_importance: [ ]
    head_type: mlp
    normalize: false # in order to perform pooling manually`1
    pool_name: identical # adaptive_max #identical
    spatial_size: 16
    softweight: 0.01

Trainer:
  pre_max_epoch: null
  ft_max_epoch: null