InfoNCEParameters:
  EncoderParams:
    head_types: mlp
    normalize: true
    method_name: simclr
    pool_method: adaptive_avg # adaptive_max #identical
  DecoderParams:
    head_types: mlp
    normalize: true
    output_size: [ 16,16 ]
    pool_method: adaptive_avg # adaptive_max #identical
  LossParams:
    temperature: 0.07

  weight: 0.1
  neigh_weight: 1

  NeighParams:
    kernel_size: 1
    margin: 3

  ContentParams:
    null



