# this is to specify the optimization configuration when considering different learning rate for encoder and decoder

OptimizerSupplementary:
  name: Adam
  base:
    lr: 0.0000001
    weight_decay: 0.00001

  group:
    feature_names: [ ]
    lr: 0.00000002
    weight_decay: 0.000001



