Trainer:
  name: null
  feature_names: [ "Conv5", ]
  feature_importance: [ 1, ]
  device: cuda
  num_batches: 500
  max_epoch: 100
  two_stage_training: false
  grad_from: null
  grad_util: null

Optim:
  name: Adam
  lr: 0.000005
  weight_decay: 0.00001

ContrastiveLoaderParams:
  group_sample_num: 7
  partition_sample_num: 1
  num_workers: 8