#!/bin/bash
#!/bin/bash
#base_folder=/lustre04/scratch/jizong/Contrast-You/semi_seg/runs/0401_acdc/githash_4519149/acdc
base_folder=/home/jizong/scratch/Contrast-You/semi_seg/runs/0420_prostate
save_dir=0420_prostate_semi

cmd_cmd="   "

source ./_run_semi $save_dir/semi_supervised \
  prostate \
  "${cmd_cmd}" \
  10

# running all things without depending on the checkpoint
run_null_checkpoint() {
  run_baseline no_checkpoint_path null null_checkpoint/null
  run_mt no_checkpoint_path null null_checkpoint/null
  run_udaiic no_checkpoint_path null null_checkpoint/null
}

run_semi_on_checkpoint() {
  run_baseline $1 yes $2
  run_mt $1 yes $2
  run_infonce $1 yes $2
  run_infonce $1 null $2
  run_mt_infonce $1 yes $2
  run_udaiic $1 yes $2
}

run_null_checkpoint
run_semi_on_checkpoint ${base_folder}/githash_a3c409b/prostate/random_seed_10/sample_num_5/global_Conv5_1.0/contrast_on_partition/self-paced/method_soft/loss_params*1.0_50.0/type_inversesquare \
  contrast_on_parition/self
run_semi_on_checkpoint ${base_folder}/githash_a3c409b/prostate/random_seed_10/sample_num_5/global_Conv5_1.0/contrast_on_partition/infonce \
  contrast_on_parition/infonce

run_semi_on_checkpoint ${base_folder}/githash_a3c409b/prostate/random_seed_10/sample_num_5/global_Conv5_1.0/contrast_on_patient/self-paced/method_soft/loss_params*2.5_60.0/type_inversesquare \
  contrast_on_patient/self
run_semi_on_checkpoint ${base_folder}/githash_a3c409b/prostate/random_seed_10/sample_num_5/global_Conv5_1.0/contrast_on_patient/infonce \
  contrast_on_patient/infonce

run_semi_on_checkpoint ${base_folder}/githash_a3c409b/prostate/random_seed_10/sample_num_5/global_Conv5_Conv5_1.0_0.001/contrast_on_partition_patient/self-paced/method_soft_soft/loss_params*1.0_70.0*2.5_40.0/type_inversesquare_inversesquare \
  contrast_on_all/self
run_semi_on_checkpoint ${base_folder}/githash_a3c409b/prostate/random_seed_10/sample_num_5/global_Conv5_Conv5_1.0_0.001/contrast_on_partition_patient/infonce \
  contrast_on_all/infonce
