#!/bin/bash

rand_seed=10
save_dir=0414_prostate
group_num=5
num_batches=200
pre_max_epoch=120
ft_max_epoch=75
dataset=prostate
comm_cmd=" -n ${dataset}  "

set -e pipefail
python run_infonce_pretrain.py ${comm_cmd} --save_dir ${save_dir} -b ${num_batches} -s ${rand_seed} --time=2 \
  baseline -e ${ft_max_epoch}

###### multitask
python run_infonce_pretrain.py ${comm_cmd} --save_dir ${save_dir} -b ${num_batches} -s ${rand_seed} --time=4 \
  infonce --global_features Conv5 --global_importance 1 --contrast_on partition -g=${group_num} \
  -pe ${pre_max_epoch} -fe ${ft_max_epoch}
#
python run_infonce_pretrain.py ${comm_cmd} --save_dir ${save_dir} -b ${num_batches} -s ${rand_seed} --time=4 \
  infonce --global_features Conv5 --global_importance 1 --contrast_on patient -g=${group_num} \
  -pe ${pre_max_epoch} -fe ${ft_max_epoch}

#### self-paced
function run_selfpaced {
  python run_infonce_pretrain.py ${comm_cmd} --save_dir ${save_dir} -b ${num_batches} -s ${rand_seed} --time=4 \
    selfpaced --global_features Conv5 --global_importance 1 --contrast_on partition -g=${group_num} \
    -pe ${pre_max_epoch} -fe ${ft_max_epoch} --begin_value $1 --end_value $2 --method $3 --scheduler_type=inversesquare

  python run_infonce_pretrain.py ${comm_cmd} --save_dir ${save_dir} -b ${num_batches} -s ${rand_seed} --time=4 \
    selfpaced --global_features Conv5 --global_importance 1 --contrast_on patient -g=${group_num} \
    -pe ${pre_max_epoch} -fe ${ft_max_epoch} --begin_value $1 --end_value $2 --method $3 --scheduler_type=inversesquare

}

run_selfpaced 4 40 soft
run_selfpaced 4 50 soft
run_selfpaced 4 60 soft
run_selfpaced 4 70 soft

run_selfpaced 3.5 40 soft
run_selfpaced 3.5 50 soft
run_selfpaced 3.5 60 soft
run_selfpaced 3.5 70 soft

run_selfpaced 3 40 soft
run_selfpaced 3 50 soft
run_selfpaced 3 60 soft
run_selfpaced 3 70 soft

run_selfpaced 2.5 40 soft
run_selfpaced 2.5 50 soft
run_selfpaced 2.5 60 soft
run_selfpaced 2.5 70 soft

run_selfpaced 2 40 soft
run_selfpaced 2 50 soft
run_selfpaced 2 60 soft
run_selfpaced 2 70 soft

run_selfpaced 1.5 40 soft
run_selfpaced 1.5 50 soft
run_selfpaced 1.5 60 soft
run_selfpaced 1.5 70 soft

run_selfpaced 1 40 soft
run_selfpaced 1 50 soft
run_selfpaced 1 60 soft
run_selfpaced 1 70 soft

function run_multi_selfpaced {
  python run_infonce_pretrain.py ${comm_cmd} --save_dir ${save_dir} -b ${num_batches} -s ${rand_seed} --time=4 \
    infonce --global_features Conv5 Conv5 --global_importance $1 $2 --contrast_on partition patient -g=${group_num} \
    -pe ${pre_max_epoch} -fe ${ft_max_epoch}

  python run_infonce_pretrain.py ${comm_cmd} --save_dir ${save_dir} -b ${num_batches} -s ${rand_seed} --time=4 \
    selfpaced --global_features Conv5 Conv5 --global_importance $1 $2 --contrast_on partition patient -g=${group_num} \
    -pe ${pre_max_epoch} -fe ${ft_max_epoch} --begin_value 1 2.5 --end_value 70 40 --method soft soft --scheduler_type inversesquare inversesquare
}
run_multi_selfpaced 1 0.001
run_multi_selfpaced 1 0.005
run_multi_selfpaced 1 0.01
run_multi_selfpaced 1 0.02
run_multi_selfpaced 1 0.05
