#!/bin/bash
run() {
  python run_script.py -n "${1}" -s 10 --lr "${2}" --save_dir=0103 -l "${3}" -b 300 --time=3
  python run_script.py -n "${1}" -s 10 --lr "${2}" --save_dir=0103 -l "${3}" -b 300 --time=3 --two_stage_training
  python run_script.py -n "${1}" -s 10 --lr "${2}" --save_dir=0103 -l "${3}" -b 300 --time=3 --two_stage_training --disable_bn
}

run_acdc() {
  run acdc "${1}" 0.02
  run acdc "${1}" 0.05
  run acdc "${1}" 0.10
}

run_acdc 0.000001

run_acdc 0.00001

run_acdc 0.0001
