#!/bin/bash
base_folder=/home/jizong/scratch/Contrast-You/semi_seg/runs/0425
save_dir=0425_semi

cmd_cmd="  "


source ./_run_semi $save_dir/semi_supervised \
  acdc \
  "${cmd_cmd}" \
  10


run_semi_on_checkpoint() {
  run_baseline $1 yes $2
  run_mt $1 yes $2
  run_infonce $1 yes $2
  run_infonce $1 null $2
  run_mt_infonce $1 yes $2
  run_udaiic $1 yes $2
}


run_semi_on_checkpoint ${base_folder}/githash_762c7fd/acdc/random_seed_20/sample_num_10/global_Conv5_1.0/contrast_on_partition/self-paced/method_soft/loss_params*1.0_80.0/type_inversesquare \
 contrast_on_parition/self

#run_semi_on_checkpoint ${base_folder}/githash_762c7fd/acdc/random_seed_30/sample_num_10/global_Conv5_1.0/contrast_on_partition/infonce \
#  contrast_on_parition/infonce
#
#run_semi_on_checkpoint ${base_folder}/githash_762c7fd/acdc/random_seed_30/sample_num_10/global_Conv5_1.0/contrast_on_cycle/self-paced/method_soft/loss_params*1.5_60.0/type_inversesquare \
#  contrast_on_cycle/self
#
#run_semi_on_checkpoint ${base_folder}/githash_762c7fd/acdc/random_seed_30/sample_num_10/global_Conv5_1.0/contrast_on_cycle/infonce \
#  contrast_on_cycle/infonce
#
#run_semi_on_checkpoint ${base_folder}/githash_762c7fd/acdc/random_seed_20/sample_num_10/global_Conv5_1.0/contrast_on_patient/self-paced/method_soft/loss_params*3.5_50.0/type_inversesquare\
#  contrast_on_patient/self
#
#run_semi_on_checkpoint ${base_folder}/githash_762c7fd/acdc/random_seed_10/sample_num_10/global_Conv5_1.0/contrast_on_patient/infonce \
#  contrast_on_patient/infonce
#
