#!/bin/bash
set -e
export CUBLAS_WORKSPACE_CONFIG=:4096:8

set -e
SAMPLE_PATH=/home/jizong/Workspace/Contrast-You/runs/beluga3/1229_combine/prostate/hash_37135ba4782/prostate/pretrain/sample

python plot_pretrain_cluster.py Trainer.save_dir=${SAMPLE_PATH}/rr_alpha_1/pretrain \
  trainer_checkpoint=${SAMPLE_PATH}/rr_alpha_1/pretrain/last.pth \
  --path ${SAMPLE_PATH}/rr_alpha_1/pretrain/config.yaml

python plot_pretrain_cluster.py Trainer.save_dir=${SAMPLE_PATH}/rr_alpha_0/pretrain \
  trainer_checkpoint=${SAMPLE_PATH}/rr_alpha_0/pretrain/last.pth \
  --path ${SAMPLE_PATH}/rr_alpha_0/pretrain/config.yaml

python plot_pretrain_cluster.py Trainer.save_dir=${SAMPLE_PATH}/rr_alpha_0.25/pretrain \
  trainer_checkpoint=${SAMPLE_PATH}/rr_alpha_0.25/pretrain/last.pth \
  --path ${SAMPLE_PATH}/rr_alpha_0.25/pretrain/config.yaml

python plot_pretrain_cluster.py Trainer.save_dir=${SAMPLE_PATH}/rr_alpha_0.5/pretrain \
  trainer_checkpoint=${SAMPLE_PATH}/rr_alpha_0.5/pretrain/last.pth \
  --path ${SAMPLE_PATH}/rr_alpha_0.5/pretrain/config.yaml



python plot_pretrain_cluster.py Trainer.save_dir=${SAMPLE_PATH}/rr_alpha_0.75/pretrain \
  trainer_checkpoint=${SAMPLE_PATH}/rr_alpha_0.75/pretrain/last.pth \
  --path ${SAMPLE_PATH}/rr_alpha_0.75/pretrain/config.yaml
