#!/bin/bash
set -e
export CUBLAS_WORKSPACE_CONFIG=:4096:8
export PYTHONOPTIMIZE=1

num_batches=250
max_epoch=45
pre_lr=0.0000005
ft_lr=0.0000001

ckpt=Arch.checkpoint=runs2/infonce/last.pth

python main.py Trainer.save_dir=infonce Trainer.name=pretrain Trainer.num_batches=${num_batches} \
  Arch.max_channel=512 Trainer.max_epoch=${max_epoch} Optim.lr=${pre_lr} --opt-path config/pretrain.yaml

python main.py ${ckpt} Trainer.save_dir=infonce/tra/scan_1 Data.labeled_data_ratio=0.01 Trainer.name=ft \
  Trainer.num_batches=${num_batches} Arch.max_channel=512 Trainer.max_epoch=${max_epoch} Optim.lr=${ft_lr}

python main.py ${ckpt} Trainer.save_dir=infonce/tra/scan_174 Data.labeled_data_ratio=1.0 Trainer.name=ft \
  Trainer.num_batches=${num_batches} Arch.max_channel=512 Trainer.max_epoch=${max_epoch} Optim.lr=${ft_lr}

ckpt=""

python main.py ${ckpt} Trainer.save_dir=baseline/tra/scan_1 Data.labeled_data_ratio=0.01 Trainer.name=ft \
  Trainer.num_batches=${num_batches} Arch.max_channel=512 Trainer.max_epoch=${max_epoch} Optim.lr=${ft_lr}

python main.py ${ckpt} Trainer.save_dir=baseline/tra/scan_174 Data.labeled_data_ratio=1.0 Trainer.name=ft \
  Trainer.num_batches=${num_batches} Arch.max_channel=512 Trainer.max_epoch=${max_epoch} Optim.lr=${ft_lr}
