CrossCorrelationParameters:
  feature_name: Up_conv2
  num_clusters: 20
  head_type: mlp
  num_subheads: 1
  save: true
  hooks:
    mi:
      weight: 0.5
      padding: 0
      lamda: 1.5
      symmetric: true
    cc:
      weight: 0.1
      kernel_size: 5
      diff_power: 0.75
    compact:
      weight: 0.01
    rr:
      weight: 0.0
      symmetric: true
      lamda: 1.5

