CrossCorrelationParameters:
  feature_name: Up_conv2
  num_clusters: 20
  head_type: linear
  num_subheads: 5
  save: true
  hooks:
    imsat:
      weight: 0.1
      lamda: 1.0
      use_dynamic: true
    consist:
      weight: 0.1
