CrossCorrelationParameters:
  feature_name: Up_conv2
  num_clusters: 20
  head_type: mlp
  num_subheads: 1
  save: true
  hooks:
    cc:
      weight: 0.1
      kernel_size: 5
      diff_power: 0.75
    rr:
      weight: 1
      symmetric: true
      lamda: 1.5
      alpha: 0.5 # 0 is the mi, 1 is the barlow-twin.
Trainer:
  enable_scale: true