CrossCorrelationParameters:
  feature_name: Up_conv2
  num_clusters: 20
  head_type: mlp
  num_subheads: 1
  save: true
  hooks:
    cc:
      weight: 1.0
      kernel_size: 5
      diff_power: 0.75
    rr:
      weight: 1.0
      symmetric: true
      lamda: 1
      alpha: 0.5 # 0 is the mi, 1 is the barlow-twin.
    align:
      weight: 0.1

Trainer:
  enable_scale: true