#!/bin/bash
num_batches=200
pre_max_epoch=120
ft_max_epoch=80
save_dir=0315

python main_finetune.py Data.name=acdc Trainer.num_batches=${num_batches} Arch.num_classes=4 RandomSeed=10 Optim.lr=0.0000001000 \
  Trainer.max_epoch=${ft_max_epoch} Trainer.name=finetune Trainer.save_dir=${save_dir}/githash_1942a72/acdc/random_seed_10/baseline

python main_infonce.py Trainer.name=experimentmultitaskpretrain InfoNCEParameters.GlobalParams.contrast_on=[patient] \
  Data.name=acdc Trainer.num_batches=${num_batches} Arch.num_classes=4 RandomSeed=10 Optim.pre_lr=null Optim.ft_lr=null \
  Trainer.pre_max_epoch=${pre_max_epoch} Trainer.ft_max_epoch=${ft_max_epoch} ContrastiveLoaderParams.group_sample_num=10 \
  ProjectorParams.GlobalParams.feature_names=[Conv5] ProjectorParams.GlobalParams.feature_importance=[1.0] \
  ProjectorParams.DenseParams.feature_names=[] ProjectorParams.DenseParams.feature_importance=[] \
  InfoNCEParameters.LossParams.exclude_other_pos=false \
  Trainer.save_dir=${save_dir}/githash_1942a72/acdc/random_seed_10/sample_num_10/normal/contrast_on_patient/infonce/global_Conv5_1.0/dense_/ \
  --opt_config_path ../config/specific/pretrain.yaml ../config/specific/infoncemultitask.yaml

python main_infonce.py Trainer.name=experimentmultitaskpretrain InfoNCEParameters.GlobalParams.contrast_on=[patient] \
  Data.name=acdc Trainer.num_batches=${num_batches} Arch.num_classes=4 RandomSeed=10 Optim.pre_lr=null Optim.ft_lr=null \
  Trainer.pre_max_epoch=${pre_max_epoch} Trainer.ft_max_epoch=${ft_max_epoch} ContrastiveLoaderParams.group_sample_num=10 \
  ProjectorParams.GlobalParams.feature_names=[Conv5] ProjectorParams.GlobalParams.feature_importance=[1.0] \
  ProjectorParams.DenseParams.feature_names=[] ProjectorParams.DenseParams.feature_importance=[] \
  InfoNCEParameters.LossParams.exclude_other_pos=false \
  SelfPacedParams.begin_value=3 SelfPacedParams.end_value=10 \
  Trainer.save_dir=${save_dir}/githash_1942a72/acdc/random_seed_10/sample_num_10/self-paced/contrast_on_patient/infonce/global_Conv5_1.0/dense_/3_10 \
  --opt_config_path ../config/specific/pretrain.yaml ../config/specific/selfpaced_infonce.yaml

python main_infonce.py Trainer.name=experimentmultitaskpretrain InfoNCEParameters.GlobalParams.contrast_on=[patient] \
  Data.name=acdc Trainer.num_batches=${num_batches} Arch.num_classes=4 RandomSeed=10 Optim.pre_lr=null Optim.ft_lr=null \
  Trainer.pre_max_epoch=${pre_max_epoch} Trainer.ft_max_epoch=${ft_max_epoch} ContrastiveLoaderParams.group_sample_num=10 \
  ProjectorParams.GlobalParams.feature_names=[Conv5] ProjectorParams.GlobalParams.feature_importance=[1.0] \
  ProjectorParams.DenseParams.feature_names=[] ProjectorParams.DenseParams.feature_importance=[] \
  InfoNCEParameters.LossParams.exclude_other_pos=false \
  SelfPacedParams.begin_value=3 SelfPacedParams.end_value=7 \
  Trainer.save_dir=${save_dir}/githash_1942a72/acdc/random_seed_10/sample_num_10/self-paced/contrast_on_patient/infonce/global_Conv5_1.0/dense_/3_7 \
  --opt_config_path ../config/specific/pretrain.yaml ../config/specific/selfpaced_infonce.yaml
