RandomSeed: 10

Arch:
  input_dim: 1
  num_classes: 4

Optim:
  name: Adam
  lr: 0.0000001
  weight_decay: 0.00001

Scheduler:
  multiplier: 200
  warmup_max: 10

Data:
  name: acdc
  labeled_data_ratio: 0.05
  unlabeled_data_ratio: 0.95

LabeledData:
  shuffle: true
  batch_size: 5
  num_workers: 5

UnlabeledData:
  shuffle: true
  batch_size: 5
  num_workers: 5

Trainer:
  feature_names: [ "Conv5", "Up_conv3", "Up_conv2" ]
  feature_importance: [ 1, 0.5, 0.5 ]
  name: partial
  save_dir: tmp
  device: cuda
  num_batches: 500
  max_epoch: 100
  two_stage_training: false
  disable_bn_track_for_unlabeled_data: false