RandomSeed: 1

Arch:
  input_dim: 1
  num_classes: 4

Data:
  labeled_data_ratio: 0.05
  unlabeled_data_ratio: 0.95

Trainer:
  name: contrast
  save_dir: test_semi_trainer
  device: cuda
  num_batches: 500
  max_epoch_train_decoder: 100
  max_epoch_train_encoder: 100
  max_epoch_train_finetune: 100
  train_encoder: True
  train_decoder: True

PretrainEncoder:
  group_option: partition

PretrainDecoder:
  null
FineTune:
  reg_weight: 15



#Checkpoint: runs/test_pipeline