PretrainConfig:
  use_pretrain: false
  Trainer:
    name: null
    feature_names: [ "Conv5", ]
    feature_importance: [ 1, ]
    device: cuda
    num_batches: 300
    max_epoch: 100

  ContrastData:
    group_sample_num: 8
    partition_sample_num: 1
    num_workers: 2
    shuffle: false

  Optim:
    name: Adam
    lr: 0.000001
    weight_decay: 0.00001

  Scheduler:
    multiplier: 300
    warmup_max: 10

  InfoNCEParameters:
    EncoderParams:
      head_types: mlp
      normalize: true
    DecoderParams:
      head_types: mlp
      normalize: true
    LossParams:
      temperature: 0.07
      base_temperature: 0.07
    weight: 1.0

  IICRegParameters:
    EncoderParams:
      num_clusters: 20
      num_subheads: 5
      head_types: linear
      normalize: false
      temperature: 1.0

    DecoderParams:
      num_clusters: 20
      num_subheads: 5
      head_types: linear
      normalize: false
      temperature: 1.0

    LossParams:
      paddings: [ 1, 3 ]
      patch_sizes: 1024

    weight: 0.1
    enforce_matching: false

  UDARegCriterion:
    name: mse # kl
    weight: 5.0