PretrainConfig:
  use_pretrain: false
  Trainer:
    feature_names: [ "Conv5", ]
    feature_importance: [ 1, ]
    device: cuda
    num_batches: 500
    max_epoch: 100

  ContrastData:
    group_sample_num: 8
    partition_sample_num: 1
    num_workers: 2
    shuffle: false

  Optim:
    name: Adam
    lr: 0.000001
    weight_decay: 0.00001

  Scheduler:
    multiplier: 300
    warmup_max: 10

  InfoNCEParameters:

    EncoderParams:
      head_types: mlp
    DecoderParams:
      head_types: mlp

    LossParams:
      temperature: 0.07
      base_temperature: 0.07