
UDARegCriterion:
  name: mse # kl
  weight: 5.0

IICRegParameters:
  EncoderParams:
    num_clusters: 20
    num_subheads: 5
    head_types: linear
    normalize: false
    temperature: 1.0

  DecoderParams:
    num_clusters: 20
    num_subheads: 5
    head_types: linear
    normalize: false
    temperature: 1.0

  LossParams:
    paddings: [ 1, 3 ]
    patch_sizes: 1024

  weight: 0.1
  enforce_matching: false

FeatureOutputIICRegParameters:
  DecoderParams:
    num_clusters: 4
    num_subheads: 5
    head_types: linear
    normalize: false

  LossParams:
    paddings: [ 1, 3 ]
    patch_sizes: 1024

  weight: 0.1
  enforce_matching: false

EntropyMinParameters:
  weight: 0.00001

MeanTeacherParameters:
  name: mse
  weight: 10
  alpha: 0.999
  weight_decay: 0.000001

MIDLPaperParameters:
  iic_weight: 0.1
  padding: 1
  patch_size: 1024


PICARegParameters:
  EncoderParams:
    num_clusters: 20
    num_subheads: 5
    head_types: linear
    normalize: false

  DecoderParams:
    num_clusters: 20
    num_subheads: 5
    head_types: linear
    normalize: false

  LossParams:
    paddings: [ 1, 3 ]

  weight: 0.1
  enforce_matching: false

InfoNCEParameters:
  EncoderParams:
    head_types: mlp
    normalize: true
  DecoderParams:
    head_types: mlp
    normalize: true
    output_size: [16,16]
  LossParams:
    temperature: 0.07
    base_temperature: 0.07
  weight: 0.1

PrototypeParameters:
  EncoderParams:
    head_types: mlp
  DecoderParams:
    head_types: mlp
  LossParams:
    temperature: 0.07
    base_temperature: 0.07
  weight: 0.1

DPrototypeParameters:
  uda_weight: 5.0
  cluster_weight: 0.1
  prototytpe_nums: 100

ExperimentParameters:
  null

#Checkpoint: runs/test_pipeline