RandomSeed: 10

Arch:
  input_dim: 1
  num_classes: 4

Optim:
  name: Adam
  lr: 0.00002
  weight_decay: 0.00001

Scheduler:
  multiplier: 400
  warmup_max: 10

Augment: strong

Data:
  labeled_data_ratio: 0.05
  unlabeled_data_ratio: 0.95

LabeledData:
  shuffle: true
  batch_size: 4
  num_workers: 4

UnlabeledData:
  shuffle: true
  batch_size: 4
  num_workers: 4

Trainer:
  feature_names: ["Up_conv4", "Up_conv3"]
  name: partial
  save_dir: tmp
  device: cuda
  num_batches: 500
  max_epoch: 100

UDARegCriterion:
  name: mse # kl
  weight: 0.1

IICRegParameters:
  IICSegcriterion:
    lamda: 1.0
    padding: 7
    patch_size: 64
  LocalCluster:
    head_types: linear
    num_subheads: 10
    num_clusters: 10
  weight: 0.1









#Checkpoint: runs/test_pipeline