RandomSeed: 10

Arch:
  input_dim: 1
  num_classes: 4

Optim:
  name: Adam
  lr: 0.0000001
  weight_decay: 0.00001

Scheduler:
  multiplier: 400
  warmup_max: 10

Augment: strong

Data:
  labeled_data_ratio: 0.05
  unlabeled_data_ratio: 0.95

LabeledData:
  shuffle: true
  batch_size: 4
  num_workers: 4

UnlabeledData:
  shuffle: true
  batch_size: 8
  num_workers: 4

Trainer:
  feature_names: ["Conv5", "Up_conv3", "Up_conv2"]
  feature_importance: [1, 0.5, 0.5]
  name: partial
  save_dir: tmp
  device: cuda
  num_batches: 500
  max_epoch: 100

UDARegCriterion:
  name: mse # kl
  weight: 0.1

IICRegParameters:
  EncoderParams:
    num_clusters: 10
    num_subheads: 5
    head_types: linear

  DecoderParams:
    num_clusters: 20
    num_subheads: 5
    head_types: mlp

  LossParams:
    paddings: 1
    patch_sizes: 128


  weight: 0.01









#Checkpoint: runs/test_pipeline