#!/bin/bash
seed=10
max_epoch=100
num_batches=300
save_dir=bn

function run_acdc_baseline {
  m=$1
  python main.py Arch.momentum=${m} RandomSeed=${seed} Data.name=acdc Trainer.max_epoch=${max_epoch} Trainer.num_batches=${num_batches} Data.labeled_scan_num=1 Trainer.save_dir=${save_dir}/acdc/moment_${m}/labeled_data_1_scan/ Trainer.name=ft
  python main.py Arch.momentum=${m} RandomSeed=${seed} Data.name=acdc Trainer.max_epoch=${max_epoch} Trainer.num_batches=${num_batches} Data.labeled_scan_num=2 Trainer.save_dir=${save_dir}/acdc/moment_${m}/labeled_data_2_scan/ Trainer.name=ft
  python main.py Arch.momentum=${m} RandomSeed=${seed} Data.name=acdc Trainer.max_epoch=${max_epoch} Trainer.num_batches=${num_batches} Data.labeled_scan_num=4 Trainer.save_dir=${save_dir}/acdc/moment_${m}/labeled_data_4_scan/ Trainer.name=ft

}
run_acdc_baseline 0.01
run_acdc_baseline 0.1
run_acdc_baseline 0.5
run_acdc_baseline 0.9
run_acdc_baseline 0.99