Arch:
  input_dim: 1
  num_classes: 4
DPrototypeParameters:
  cluster_weight: 0.1
  prototytpe_nums: 100
  uda_weight: 5.0
Data:
  labeled_data_ratio: 0.05
  name: acdc
  unlabeled_data_ratio: 0.95
DistributedTrain: false
EntropyMinParameters:
  weight: 1.0e-05
FeatureOutputIICRegParameters:
  DecoderParams:
    head_types: linear
    normalize: false
    num_clusters: 4
    num_subheads: 5
  LossParams:
    paddings:
    - 1
    - 3
    patch_sizes: 1024
  enforce_matching: false
  weight: 0.1
GITHASH: 82ea3e0c47917b8aaf51f02dfeb7f37629c63b4e
IICRegParameters:
  DecoderParams:
    head_types: linear
    normalize: false
    num_clusters: 20
    num_subheads: 5
    temperature: 1.0
  EncoderParams:
    head_types: linear
    normalize: false
    num_clusters: 20
    num_subheads: 5
    temperature: 1.0
  LossParams:
    paddings:
    - 1
    - 3
    patch_sizes: 1024
  enforce_matching: false
  weight: 0.1
InfoNCEParameters:
  DecoderParams:
    head_types: mlp
    normalize: true
  EncoderParams:
    head_types: mlp
    normalize: true
  LossParams:
    base_temperature: 0.07
    temperature: 0.07
  weight: 0.1
LabeledData:
  batch_size: 5
  num_workers: 3
  shuffle: true
MIDLPaperParameters:
  iic_weight: 0.1
  padding: 1
  patch_size: 1024
MeanTeacherParameters:
  alpha: 0.999
  name: mse
  weight: 10
  weight_decay: 1.0e-06
Optim:
  lr: 1.0e-07
  name: Adam
  weight_decay: 1.0e-05
PICARegParameters:
  DecoderParams:
    head_types: linear
    normalize: false
    num_clusters: 20
    num_subheads: 5
  EncoderParams:
    head_types: linear
    normalize: false
    num_clusters: 20
    num_subheads: 5
  LossParams:
    paddings:
    - 1
    - 3
  enforce_matching: false
  weight: 0.1
PretrainConfig:
  Trainer:
    feature_importance:
    - 1
    - 1
    - 1
    feature_names:
    - Conv5
    - Up_conv3
    - Up_conv2
    name: infoncepretrain
PrototypeParameters:
  DecoderParams:
    head_types: mlp
  EncoderParams:
    head_types: mlp
  LossParams:
    base_temperature: 0.07
    temperature: 0.07
  weight: 0.1
RandomSeed: 8
Scheduler:
  multiplier: 400
  warmup_max: 10
Trainer:
  device: cuda
  feature_importance:
  - 1
  - 1
  - 1
  feature_names:
  - Conv5
  - Up_conv3
  - Up_conv2
  max_epoch: 100
  name: partial
  num_batches: 300
  only_labeled_data: false
  save_dir: 1211_pretrain_finetune5/acdc/label_data_ration_0.05/single_stage_training/random_seed_8/Conv5_Up_conv3_Up_conv2/pretrain/infonce
  two_stage_training: false
UDARegCriterion:
  name: mse
  weight: 5.0
UnlabeledData:
  batch_size: 5
  num_workers: 5
  shuffle: true
